server {
    listen 80;
    server_name localhost;

    location /projeto-korp {
        # Encaminha requisições feitas na porta 80 para o serviço na porta 8080
        proxy_pass http://http-server-projeto-korp:8080;
        
        # Repassa os cabeçalhos originais para que a aplicação saiba a origem da requisição
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}